# Generated by Django 3.0.11 on 2021-11-15 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='balance',
        ),
    ]
