# Generated by Django 3.0.11 on 2021-11-24 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment_management', '0003_auto_20211124_1442'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='sponsor',
            new_name='sponsor_id',
        ),
    ]
