# Generated by Django 3.0.11 on 2021-11-24 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_management', '0004_auto_20211124_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
