# Generated by Django 3.0.11 on 2021-11-25 11:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment_management', '0005_payment_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='sponsor_id',
        ),
        migrations.CreateModel(
            name='sponsor_payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('debit', models.FloatField()),
                ('credit', models.FloatField()),
                ('date', models.DateField()),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sponsor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment_management.sponsor')),
            ],
        ),
    ]
