# Generated by Django 3.0.14 on 2022-06-03 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_management', '0004_student_sponsor_id'),
        ('payment_management', '0006_auto_20211125_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor_payment',
            name='student_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student_management.student'),
        ),
    ]
