# Generated by Django 3.0.11 on 2021-09-17 07:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='enrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=150)),
                ('full_name', models.CharField(max_length=150)),
                ('curriculum_name', models.CharField(max_length=150)),
                ('academic_year', models.CharField(max_length=50)),
                ('trimester', models.CharField(max_length=50)),
                ('year_level', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=150)),
                ('scholarship', models.FloatField()),
                ('total_units', models.FloatField()),
                ('gross_fee', models.FloatField()),
                ('assessed_amount', models.FloatField()),
                ('enrollment_fee', models.FloatField()),
                ('prelim', models.FloatField()),
                ('midterm', models.FloatField()),
                ('finals', models.FloatField()),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
