# Generated by Django 3.0.11 on 2022-01-13 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment_management', '0004_auto_20220113_2217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='curriculum_id',
        ),
    ]
