# Generated by Django 3.0.11 on 2021-09-03 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='pre_requisite',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
