# Generated by Django 3.0.11 on 2022-01-13 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grade_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grades',
            name='subject_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='grades',
            name='unit',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='grades',
            name='subject_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
