# Generated by Django 3.0.11 on 2022-01-13 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grade_management', '0002_auto_20220114_0648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grades',
            name='subject_code',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='grades',
            name='subject_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='grades',
            name='unit',
            field=models.IntegerField(),
        ),
    ]
