# Generated by Django 3.0.11 on 2022-01-13 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grade_management', '0007_auto_20220114_0718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grades',
            name='numerical_grade',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='grades',
            name='percentage_grade',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='grades',
            name='trimester',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='grades',
            name='unit',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='grades',
            name='year',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
