# Generated by Django 3.0.11 on 2021-08-26 05:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shs_student_id', models.CharField(blank=True, max_length=20, null=True)),
                ('strand', models.CharField(blank=True, max_length=150, null=True)),
                ('college_student_id', models.CharField(blank=True, max_length=20, null=True)),
                ('course', models.CharField(blank=True, max_length=150, null=True)),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('birthday', models.DateField()),
                ('gender', models.CharField(max_length=50)),
                ('civil_status', models.CharField(max_length=50)),
                ('contact_number', models.CharField(max_length=50)),
                ('parent_contact_number', models.CharField(max_length=50)),
                ('city_province', models.CharField(max_length=150)),
                ('brgy', models.CharField(max_length=150)),
                ('father_name', models.CharField(max_length=50)),
                ('mother_name', models.CharField(max_length=50)),
                ('elementary_school', models.CharField(blank=True, max_length=100, null=True)),
                ('junior_high_school', models.CharField(blank=True, max_length=100, null=True)),
                ('senior_high_school', models.CharField(blank=True, max_length=100, null=True)),
                ('college', models.CharField(blank=True, max_length=100, null=True)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
