# Generated by Django 3.0.11 on 2021-09-24 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management', '0002_auto_20210827_0705'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='scholarship_percentage',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
