# Generated by Django 3.0.14 on 2022-06-03 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment_management', '0006_auto_20211125_1926'),
        ('student_management', '0003_student_scholarship_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='sponsor_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payment_management.sponsor'),
        ),
    ]
